//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimbingCompetition {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListHeaderStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListHeaderStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClimbingCompetition.ListHeaderStrings", typeof(ListHeaderStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Г.р..
        /// </summary>
        internal static string AGE {
            get {
                return ResourceManager.GetString("AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боулдеринг.
        /// </summary>
        internal static string BOULDERNAME {
            get {
                return ResourceManager.GetString("BOULDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия, Имя.
        /// </summary>
        internal static string CLIMBER {
            get {
                return ResourceManager.GetString("CLIMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инд.№.
        /// </summary>
        internal static string IID {
            get {
                return ResourceManager.GetString("IID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудность.
        /// </summary>
        internal static string LEADNAME {
            get {
                return ResourceManager.GetString("LEADNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мин..
        /// </summary>
        internal static string MINUTE {
            get {
                return ResourceManager.GetString("MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кв..
        /// </summary>
        internal static string NEXTROUND {
            get {
                return ResourceManager.GetString("NEXTROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        internal static string POS {
            get {
                return ResourceManager.GetString("POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to преКв..
        /// </summary>
        internal static string PREQF {
            get {
                return ResourceManager.GetString("PREQF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Балл.
        /// </summary>
        internal static string PTS {
            get {
                return ResourceManager.GetString("PTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разр..
        /// </summary>
        internal static string QF {
            get {
                return ResourceManager.GetString("QF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейт..
        /// </summary>
        internal static string RANKING {
            get {
                return ResourceManager.GetString("RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рез-т.
        /// </summary>
        internal static string RESULT {
            get {
                return ResourceManager.GetString("RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Протокол результатов.
        /// </summary>
        internal static string RESULTLIST {
            get {
                return ResourceManager.GetString("RESULTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трасса.
        /// </summary>
        internal static string ROUTE {
            get {
                return ResourceManager.GetString("ROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зам. гл. судьи по виду.
        /// </summary>
        internal static string ROUTEJUDGE {
            get {
                return ResourceManager.GetString("ROUTEJUDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость.
        /// </summary>
        internal static string SPEEDNAME {
            get {
                return ResourceManager.GetString("SPEEDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ст.№.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартовый протокол.
        /// </summary>
        internal static string STARTLIST {
            get {
                return ResourceManager.GetString("STARTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда.
        /// </summary>
        internal static string TEAM {
            get {
                return ResourceManager.GetString("TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контрольное время.
        /// </summary>
        internal static string TIMECLIMB {
            get {
                return ResourceManager.GetString("TIMECLIMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытие зоны изоляции.
        /// </summary>
        internal static string TIMEISOCLOSE {
            get {
                return ResourceManager.GetString("TIMEISOCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытие зоны изоляции.
        /// </summary>
        internal static string TIMEISOOPEN {
            get {
                return ResourceManager.GetString("TIMEISOOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр трассы.
        /// </summary>
        internal static string TIMEOBSERVATION {
            get {
                return ResourceManager.GetString("TIMEOBSERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string TIMERES {
            get {
                return ResourceManager.GetString("TIMERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время старта.
        /// </summary>
        internal static string TIMESTART {
            get {
                return ResourceManager.GetString("TIMESTART", resourceCulture);
            }
        }
    }
}
