//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimbingCompetition {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClimbingCompetition.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Г.р..
        /// </summary>
        public static string AGE {
            get {
                return ResourceManager.GetString("AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string BIB {
            get {
                return ResourceManager.GetString("BIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инд.№.
        /// </summary>
        public static string BIB_F {
            get {
                return ResourceManager.GetString("BIB_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боулдеринг.
        /// </summary>
        public static string BOULDER {
            get {
                return ResourceManager.GetString("BOULDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боулд..
        /// </summary>
        public static string BOULDER_S {
            get {
                return ResourceManager.GetString("BOULDER_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия, Имя.
        /// </summary>
        public static string CLIMBER_NAME {
            get {
                return ResourceManager.GetString("CLIMBER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Многоборье.
        /// </summary>
        public static string COMBINED {
            get {
                return ResourceManager.GetString("COMBINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мн..
        /// </summary>
        public static string COMBINED_S {
            get {
                return ResourceManager.GetString("COMBINED_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дискв..
        /// </summary>
        public static string DSQ {
            get {
                return ResourceManager.GetString("DSQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правка.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string GENDER {
            get {
                return ResourceManager.GetString("GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        public static string GROUP {
            get {
                return ResourceManager.GetString("GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт загрузка фотографий из папки; .
        /// </summary>
        public static string IMG_LOAD_F {
            get {
                return ResourceManager.GetString("IMG_LOAD_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт загрузка фотографий с удалённого сервера; .
        /// </summary>
        public static string IMG_LOAD_REM {
            get {
                return ResourceManager.GetString("IMG_LOAD_REM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт загрузка фотографий в папку; .
        /// </summary>
        public static string IMG_SAV_F {
            get {
                return ResourceManager.GetString("IMG_SAV_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт загрузка фотографий на удалённый сервер; .
        /// </summary>
        public static string IMG_SAV_REM {
            get {
                return ResourceManager.GetString("IMG_SAV_REM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудность.
        /// </summary>
        public static string LEAD {
            get {
                return ResourceManager.GetString("LEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тр..
        /// </summary>
        public static string LEAD_S {
            get {
                return ResourceManager.GetString("LEAD_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Подключиться к базе данных.
        /// </summary>
        public static string MF_CONNECT_MENU {
            get {
                return ResourceManager.GetString("MF_CONNECT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Отсоединиться от базы данных%NEWLINE%Смена данных подключения.
        /// </summary>
        public static string MF_DISCONNECT_MENU {
            get {
                return ResourceManager.GetString("MF_DISCONNECT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет соединения с БД.
        /// </summary>
        public static string MF_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("MF_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить трансляцию.
        /// </summary>
        public static string MF_START_TR_MENU {
            get {
                return ResourceManager.GetString("MF_START_TR_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить трансляцию.
        /// </summary>
        public static string MF_STOP_TR_MENU {
            get {
                return ResourceManager.GetString("MF_STOP_TR_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to н/я.
        /// </summary>
        public static string NYA {
            get {
                return ResourceManager.GetString("NYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разряд.
        /// </summary>
        public static string QF {
            get {
                return ResourceManager.GetString("QF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -все группы-.
        /// </summary>
        public static string SCR_ALL_GROUPS {
            get {
                return ResourceManager.GetString("SCR_ALL_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -все команды-.
        /// </summary>
        public static string SCR_ALL_TEAMS {
            get {
                return ResourceManager.GetString("SCR_ALL_TEAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определить автоматически.
        /// </summary>
        public static string SCR_DEFAULT_GROUP {
            get {
                return ResourceManager.GetString("SCR_DEFAULT_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ж.
        /// </summary>
        public static string SCR_FEMALE {
            get {
                return ResourceManager.GetString("SCR_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздн. заявка.
        /// </summary>
        public static string SCR_LATE_APPL {
            get {
                return ResourceManager.GetString("SCR_LATE_APPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список участников.
        /// </summary>
        public static string SCR_LIST_TITLE {
            get {
                return ResourceManager.GetString("SCR_LIST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов.номер.
        /// </summary>
        public static string SCR_NEW_BIB {
            get {
                return ResourceManager.GetString("SCR_NEW_BIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участие в видах.
        /// </summary>
        public static string SCR_PARTICIPATIONS {
            get {
                return ResourceManager.GetString("SCR_PARTICIPATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг (место).
        /// </summary>
        public static string SCR_RANK_ALL {
            get {
                return ResourceManager.GetString("SCR_RANK_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейт.Боулд..
        /// </summary>
        public static string SCR_RANK_BOULDER_COL {
            get {
                return ResourceManager.GetString("SCR_RANK_BOULDER_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейт.Мн..
        /// </summary>
        public static string SCR_RANK_COMBINED_COL {
            get {
                return ResourceManager.GetString("SCR_RANK_COMBINED_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейт.Тр..
        /// </summary>
        public static string SCR_RANK_LEAD_COL {
            get {
                return ResourceManager.GetString("SCR_RANK_LEAD_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейт.Ск..
        /// </summary>
        public static string SCR_RANK_SPEED_COL {
            get {
                return ResourceManager.GetString("SCR_RANK_SPEED_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость.
        /// </summary>
        public static string SPEED {
            get {
                return ResourceManager.GetString("SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ск..
        /// </summary>
        public static string SPEED_S {
            get {
                return ResourceManager.GetString("SPEED_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string SURNAME {
            get {
                return ResourceManager.GetString("SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда.
        /// </summary>
        public static string TEAM {
            get {
                return ResourceManager.GetString("TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт обновление сайта; .
        /// </summary>
        public static string UPD_REM {
            get {
                return ResourceManager.GetString("UPD_REM", resourceCulture);
            }
        }
    }
}
